require("plugins.tree-sitter")
require("plugins.ui")
require("plugins.neo-tree")
require("plugins.which-key")
require("plugins.gitsigns")
require("plugins.lualine")
require("plugins.bufferline")
require("plugins.telescope")
require("plugins.completion")
require("plugins.trouble")
require("plugins.fterm")

require("plugins.lsp.lspconfig")
require("plugins.lsp.null-ls")
